version: 2
updates:
  - package-ecosystem: *
    directory: "/"
    schedule:
      interval: daily
    labels:
      - Update dependencies
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch
