version: 2
updates:
  - package-ecosystem: *
    directory: "/"
    schedule:
      interval: daily
    labels:
      - Update dependencies
    ignore:
      - dependency-name: "*"
        update-types:
          - version-update:semver-minor
          - version-update:semver-patch


version: 2
updates:
  - package-ecosystem: "composer"
    # Files stored in repository root
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "Maven"
    # Files stored in `app` directory
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-action"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    # Workflow files stored in the
    # default location of `.github/workflows`
    directory: "/"
    schedule:
      interval: "weekly"
